### ISSUE TITLE
CommandHandler loads commands from subfolders several times

### ISSUE THREAD

**Issue by D3rise** [discord-akairo/discord-akairo#106]
**When trying to `loadAll()` commands from folder, that contains subfolders of command files, command handler is trying to load those files second time.** 
But before I will tell you what problem is, I would like to mention that I use TypeScript and custom `Command` class:
```js
import { Command, CommandOptions } from "discord-akairo";
import { Repository, getRepository } from "typeorm";
import { Guild } from "../entity/Guild.entity";
import { Search } from "../entity/Search.entity";
import { Chat } from "../entity/Chat.entity";
import { User } from "../entity/User.entity";
import CustomClient from "./Client";
import { Report } from "../entity/Report.entity";
import { Message } from "discord.js";
import i18n from "i18n";

class CustomCommand extends Command {
  client: CustomClient;
  guildRepository: Repository<Guild>;
  searchRepository: Repository<Search>;
  chatRepository: Repository<Chat>;
  userRepository: Repository<User>;
  reportRepository: Repository<Report>;
  user: User;
  guild: Guild;
  chat: Chat;
  userChatId: string;

  constructor(id: string, options?: CommandOptions) {
    super(id, options);
    this.guildRepository = getRepository(Guild);
    this.searchRepository = getRepository(Search);
    this.chatRepository = getRepository(Chat);
    this.userRepository = getRepository(User);
    this.reportRepository = getRepository(Report);
  }

  async before(message: Message) {
    this.user = await this.userRepository.findOne({
      userId: message.author.id
    });
    i18n.setLocale(this.user.locale);

    this.chat = await this.chatRepository.findOne({
      where: [
        {
          user1Id: this.user.userId,
          endedAt: null
        },
        {
          user2Id: this.user.userId,
          endedAt: null
        }
      ]
    });

    if (this.chat) {
      this.userChatId =
        this.chat.user1Id === message.author.id ? "user1Id" : "user2Id";
    }

    if (message.guild) {
      this.guild = await this.guildRepository.findOne({
        where: { discordId: message.guild.id }
      });
    }
  }
}

export default CustomCommand;
```
The error log is:
```
(node:6340) UnhandledPromiseRejectionWarning: AkairoError [ALREADY_LOADED]: Command 'config-guild' is already loaded
    at CommandHandler.load (C:\Users\deris\Documents\Projects\AnonChats\node_modules\discord-akairo\src\struct\AkairoHandler.js:137:45)
    at CommandHandler.loadAll (C:\Users\deris\Documents\Projects\AnonChats\node_modules\discord-akairo\src\struct\AkairoHandler.js:156:40)
    at CustomClient.initHandlers (C:\Users\deris\Documents\Projects\AnonChats\dist\struct\Client.js:105:29)
    at CustomClient.init (C:\Users\deris\Documents\Projects\AnonChats\dist\struct\Client.js:53:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

This is my folder structure for `commands` folder, that I specified in `directory` property for `CommandHandler` in my `Client` class:
```
commands
├── bot
│   ├── help.ts
│   ├── info.ts
│   ├── invite.ts
│   └── ping.ts
├── chat
│   ├── deanon.ts
│   ├── game.ts
│   ├── report.ts
│   ├── search.ts
│   ├── stop.ts
│   └── stopSearch.ts
└── config
    ├── config-guild.ts
    ├── config.ts
    ├── language.ts
    └── prefix.ts
```
And I checked several times that all of those files contains unique ids.

I've tried to do some experiment with those problem and write `this.commandHandler.on("load", command => console.log(command.aliases[0]));` in my `Client` class and that what I have:
```
help
stats
invite
ping
deanon
game
report
search
stop
stop-search
config-guild
config
language
prefix
(node:6340) UnhandledPromiseRejectionWarning: AkairoError [ALREADY_LOADED]: { error log that I have write above }
```

**So, I can tell that `CommandHandler` is trying to read dirs with commands the second time, when all commands are already loaded.**

**Comment by ItsPapaia** [comment]
Akairo loads by ID, not aliases, try to log `command.id` on load and see if you have two (or more) modules with the same ID, as this has never happened to me.

**Comment by Aeryle** [comment]
It technically is impossible to load twice with the same ID for two reasons, one is that akairo will error the second one is that because they are Collections, if you set again with the same ID, it will just override the first command, not add another entry

**Comment by D3rise** [comment]
Result is the same
![image](https://user-images.githubusercontent.com/34286268/77537065-86041200-6eae-11ea-8e93-c39aa57c38e8.png)

**Comment by Aeryle** [comment]
Check your files 1 by 1 then, you have a duplicated ID somewhere, impossible otherwise, never had this bug, and this kind of fail happens often

**Comment by D3rise** [comment]
> Check your files 1 by 1 then, you have a duplicated ID somewhere, impossible otherwise, never had this bug, and this kind of fail happens often

Checked. Check the log and updated comment above.

**Comment by ItsPapaia** [comment]
Well I have no idea, do you call it twice?

**Comment by Aeryle** [comment]
The weird thing is that it doesn't looks like loading them in the same order, do you have any kind of require to this particular command, or maybe a manual `load` somewhere?

**Comment by ItsPapaia** [comment]
could you put the code in some repo for us to see the whole thing?

**Comment by D3rise** [comment]
> could you put the code in some repo for us to see the whole thing?

https://github.com/D3rise/anonymous-chats-discord/tree/dev

**Comment by ItsPapaia** [comment]
does it only happen with sub-folders or with all in the same folder too?

**Comment by D3rise** [comment]
only with subfolders

**Comment by ItsPapaia** [comment]
what if you didn't shard?

**Comment by D3rise** [comment]
> what if you didn't shard?

Nope.
![image](https://user-images.githubusercontent.com/34286268/77539847-117fa200-6eb3-11ea-9224-37e8dfe9f490.png)

**Comment by ItsPapaia** [comment]
versions?

**Comment by D3rise** [comment]
in package.json of the repo that I send above

**Comment by Aeryle** [comment]
Can you run this `this.commandHandler.on('load', c = console.log(c.id) || c.remove())`
This will log and unload, I'm curious to see if every command is loaded twice or not

**Comment by D3rise** [comment]
> Can you run this `this.commandHandler.on('load', c => console.log(c.id) || c.remove())`
> This will log and unload, I'm curious to see if every command is loaded twice or not

Your code returns an error while compiling because of "type 'void' cannot be tested for truthiness", so I changed it a little and that what I got:
![image](https://user-images.githubusercontent.com/34286268/77540496-3b859400-6eb4-11ea-8a92-d8fb9dd1c211.png)

**Comment by Eastborn** [comment]
This happened to me as well, but when i filetered on .js files in the loadall function it was working i guess, so i think its trying to load the .ts file (at least for me)

**Comment by 1Computer1** [comment]
If you are using TypeScript, most likely it is because of #99. Make sure your compiled output is in a different root directory.

**Comment by megalon** [comment]
For anyone else like me who's bad at TypeScript like me:
If you move a command into a subfolder, tsc will not remove the old file by default, and you will end up with two copies of your command file in your build folder.
Double check that you don't have two copies of the same file in your build folder.

**Comment by ridays2001** [comment]
I had a problem similar to this. But, I figured out that it was because of the duplicate files. To avoid this problem in the future, I use a module called `rimraf` that deletes a folder. You can also use the basic delete command, but it didn't work for me (flags didn't work in npm scripts for some reason, so doing `del -r dist` was hard), so I am using rimraf. I set my npm scripts to `"start": "rimraf dist && tsc && node ."`

**Comment by D3rise** [comment]
> I had a problem similar to this. But, I figured out that it was because of the duplicate files. To avoid this problem in the future, I use a module called `rimraf` that deletes a folder. You can also use the basic delete command, but it didn't work for me (flags didn't work in npm scripts for some reason, so doing `del -r dist` was hard), so I am using rimraf. I set my npm scripts to `"start": "rimraf dist && tsc && node ."`
> That would delete the dist folder and compile everything again.

This was an actual solution. Thanks!
