### ISSUE TITLE
NSFW Boolean Prop on Command Class please

### ISSUE THREAD

**Issue by danrleylfd** [discord-akairo/discord-akairo#121]

**Comment by zfbx** [comment]
That's a complicated suggestion. how would you handle DMs? would they default as sfw? or be allowed to use nsfw? You could just add a userPermission function like this in your nsfw functions
```
userPermissions(message) {
        if (message.channel.nsfw) return null;
        return message.util.send('This command can only run in NSFW channels');
}
```
