### ISSUE TITLE
Test ping-pong not work.

### ISSUE THREAD

**Issue by milrak** [discord-akairo/discord-akairo#123]
I'm using:

- Node - 10
- Discord.js 12.2.0
- Discord-Akairo - 8

I can start the bot normally

bot.js
```
const { AkairoClient, CommandHandler } = require('discord-akairo');

class AnoregBot extends AkairoClient {
    constructor() {
        super({
            ownerID: '709871375099101275',
        }, {
            disableEveryone: true
        });
        this.commandHandler = new CommandHandler(this, {
            directory: './commands/',
            prefix: '!'
        });
    }
}

const anoregBot = new AnoregBot();
anoregBot.login('NzA5ODcxMzc1MDk5MTAxMjc1.Xr2aBQ.WpC_HUbBgqviTDSJbzKin3i81os');

anoregBot.once("ready", () => {
    console.log(`Logged in as ${anoregBot.user.tag}!`)

})
```

folder commands file ping-command.js
```
const { Command } = require('discord-akairo');

class PingCommand extends Command {
    constructor() {
        super('ping', {
           aliases: ['ping'] 
        });
    }

    exec(message) {
        return message.reply('Pong!');
    }
}

module.exports = PingCommand;
```
When I run `node bot.js` , the bot does not respond.

I followed the example: https://discord-akairo.github.io/#/docs/main/master/basics/commands

**Comment by ItsPapaia** [comment]
Use absolute paths for directories.
Also, Discord.js v12 requires node 12+, and this is a question for the [support server](https://discord.gg/arTauDY).

**Comment by milrak** [comment]
> Use absolute paths for directories.
> Also, Discord.js v12 requires node 12+, and this is a question for the [support server](https://discord.gg/arTauDY).

About Discord.js
"v12 requires Node 12.x or higher to use, so make sure you're up-to-date." [Before You Start](https://discordjs.guide/additional-info/changes-in-v12.html#before-you-start)

It still didn't work!

Tony#1275 asked me to add `this.commandHandler.loadAll();`

```
class AnoregBot extends AkairoClient {
    constructor() {
        super({
            ownerID: '709871375099101275',
        }, {
            disableEveryone: true
        });
        this.commandHandler = new CommandHandler(this, {
            directory: './commands/',
            prefix: '!'
        });
       
        this.commandHandler.loadAll();
    }
}
```

And it finally worked!

Thank you very much for your observation, without this I would not have succeeded!
