### ISSUE TITLE
Question: Is there a way to perform actions on startup?

### ISSUE THREAD

**Issue by kluxa** [discord-akairo/discord-akairo#126]
There are some actions that I want my bot to perform on startup. When I used the discord.js client this was simple as I could just pass the client to every event handler.

**discord-js/bot.js**
```js
fs.readdir('./events', (err, files) => {
    files.forEach(file => {
        const eventHandler = require(`./events/${file}`);
        const eventName = file.split('.')[0];
        client.on(eventName, (...args) => eventHandler(client, ...args));
    });
});
```

Then I could access the client in the 'ready' event:

**discord-js/events/ready.js**
```js
const ready = (client) => {
    console.log(`Ready! (Username: ${client.user.username}, ` +
                `ID: ${client.user.id})`);	
    doStuff(client);
}

module.exports = ready;
```

Is there a way to achieve a similar thing with discord-akairo? My ready listener looks like this:

**discord-akairo/listeners/ReadyListener.ts**
```ts
export default class ReadyListener extends Listener {
    constructor() {
        super('ready', {
            category: 'client',
            emitter: 'client',
            event: 'ready',
        });
    }

    public exec(): void {
        console.log('Ready!');
    }
}
```

**Comment by Papaia** [comment]
Yeah, just put it in the listener's `exec`, also, move to the [Discord server](https://discord.gg/arTauDY).
