### ISSUE TITLE
REQEST: add a description option for a command

### ISSUE THREAD

**Issue by Suyashtnt** [discord-akairo/discord-akairo#127]
when you create a command you could also add a description to it. Maybe ill try to add it and make a PR but this would be really useful for help commands and similar things.

**Comment by Papaia** [comment]
You can.
Passing a `description` prop in the command options would attach the given value (can be `any`) to the command.
I've seen places where an object is passed, and places there a string is passed.
If you prefer it being explicit, you can extend the class and go to town.

**Comment by Suyashtnt** [comment]
> You can.
> Passing a `description` prop in the command options would attach the given value (can be `any`) to the command.
> I've seen places where an object is passed, and places there a string is passed.
> If you prefer it being explicit, you can extend the class and go to town.

I'm an absolute noob so would I just after the `args` value just put `description: "description"`

**Comment by Papaia** [comment]
could be `description: 'A cool command!',` or
```js
description: {
  text: 'A cool command!',
  usage: '<name>',
  examples: ['Papaia', 'Superman'],
},
```

**Comment by Suyashtnt** [comment]
ok, but how can I access this in another command?

**Comment by Papaia** [comment]
get the command however you like, then it's simply `command.description`.

**Comment by Suyashtnt** [comment]
ok, thanks! I'm closing this issue but how can you get all the commands at once?
