### ISSUE TITLE
TypeError: Cannot set property 'variables' of undefined

### ISSUE THREAD

**Issue by Mzato0001** [discord-akairo/discord-akairo#129]
It not set in the database and i get that error.

https://github.com/discord-akairo/discord-akairo/blob/fd125b19fe6afd0fac30a94c20a94a9e79cc23da/src/providers/MongooseProvider.js#L60
`key = 'variables'`

**Comment by 1Computer1** [comment]
@Zerefdev

**Comment by Zerefdev** [comment]
what error do you get?

**Comment by Zerefdev** [comment]
@Mzato0001 add minimize for false in your mongoose schema, otherwise this `settings: {}` won't  be added to your database.
https://github.com/discord-akairo/discord-akairo/blob/fd125b19fe6afd0fac30a94c20a94a9e79cc23da/src/providers/MongooseProvider.js#L99-L103

**Comment by Mzato0001** [comment]
Ty but im not use mongoose anymore
