### ISSUE TITLE
peerDependencies sqlite and sequelize should be listed as optional

### ISSUE THREAD

**Issue by mvastola** [discord-akairo/discord-akairo#133]
Currently, not using the `sqlite` and/or `sequelize` packages in your `package.json` produces the following persistent error:
`npm WARN discord-akairo@8.0.0 requires a peer of sqlite@^3.0.3 but none is installed. You must install peer dependencies yourself.`

Instead, these dependencies should be listed as optional in the  `package.json` file. This will prevent the misleading message that they are 'required' when they are not.

This can be done by simply adding the following object to `package.json`.
```js
"peerDependencies": {
  "sqlite": "^3.0.3",
  "sequelize": "^5.2.12"
},
```

**Comment by Zerefdev** [comment]
#120

**Comment by Papaia** [comment]
that object is there 😕
and it is clearly a harmless warning.

**Comment by mvastola** [comment]
@Papaia (and @Zerefdev) it isn't in master. And in looking for [the changes made](https://github.com/discord-akairo/discord-akairo/pull/120/commits/0b62d10b2ffbe2f5d8f627f71995b3913bc95be7) by your commit in #120 (0b62d1), this message is showing:
`This commit does not belong to any branch on this repository. `

I think maybe that commit was merged into a branch in this repo that was never merged with `master` and has since been deleted..

And yeah, it's harmless. It's just annoying for people who are OCD about an error showing up every time you install/update a package. :wink: And, regardless, it's literally not true that it's required, and could mislead people into installing it unnecessarily.

**Comment by Zerefdev** [comment]
@mvastola it is not an error, but a warning. It is fine to ignore. 
And before downloading any package, people usually check installation/setup guide.
Akairo documentation explicitly says: `If you feel like working with SQLite or Sequelize later, install them too.`
https://discord-akairo.github.io/#/docs/main/8.0.0/basics/setup

IMO it is no big deal, even for people with OCD.

**Comment by mvastola** [comment]
I think you overestimate the degree to which people read the docs in their entirety. :stuck_out_tongue: 
But I agree it's not a big deal. It was just an annoyance I thought could be corrected, and I didn't see any downside in making the configuration/warnings more accurate. 

It seems like we're not going to agree though, so I'll close this.
