### ISSUE TITLE
Wrong type of CommandHandler#cooldowns

### ISSUE THREAD

**Issue by Mzato0001** [discord-akairo/discord-akairo#137]
https://github.com/discord-akairo/discord-akairo/blob/4b76c8f8109453cc882ad6263c4b3c0d750ec3e8/src/index.d.ts#L202
this is the wrong type of cooldowns collection 
the right type is
```ts
public cooldowns: Collection<Snowflake, { [key: string]: CooldownData }>
```

**Comment by Papaia** [comment]
This is true both in the docs
https://github.com/discord-akairo/discord-akairo/blob/master/src/struct/commands/CommandHandler.js#L719-L722
and typings
https://github.com/discord-akairo/discord-akairo/blob/master/src/index.d.ts#L202
