### ISSUE TITLE
TypeError: Cannot read property 'timer' of undefined

### ISSUE THREAD

**Issue by Mzato0001** [discord-akairo/discord-akairo#141]
https://github.com/discord-akairo/discord-akairo/blob/b57bf937930d34d38eca7af8e8e20c30d406a770/src/struct/commands/CommandHandler.js#L726

```error
TypeError: Cannot read property 'timer' of undefined
at /app/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:726:80
```

**Comment by 1Computer1** [comment]
Could you describe when this occurs?

**Comment by Mzato0001** [comment]
@1Computer1 idk i just see that in the logs many times and it crash my application
