### ISSUE TITLE
Support for custom discord.js-compatible implementation?

### ISSUE THREAD

**Issue by minhducsun2002** [discord-akairo/discord-akairo#143]
I have a fork of discord.js with several patches on top. Since `discord-akairo` `require`s `discord.js` exactly, it looks like using an alternative implementation for it is not possible without directly patching Akairo itself.

Could you add an option to leverage a custom implementation of discord.js?

**Comment by 1Computer1** [comment]
No. Fork akairo or fork discord.js.

**Comment by ravener** [comment]
If it's a fork without a name change then just install that instead of discord.js, akairo does not explicitly declare d.js as a dependency
