### ISSUE TITLE
MongooseProvider not present on providers directory

### ISSUE THREAD

**Issue by enbermudez** [discord-akairo/discord-akairo#144]
I just made a fresh installation of the discord-akairo library and there is no MongooseProvider inside the provider directory.

- [SS of the directory](https://i.ibb.co/K9CYpkQ/Captura-de-Pantalla-2020-08-06-a-la-s-13-06-46.png)

**Comment by Papaia** [comment]
The MongooseProvider is only present on the master branch, not present on npm.

**Comment by enbermudez** [comment]
Is there any reason for it?

**Comment by 1Computer1** [comment]
I'll have a release soon.

**Comment by 1Computer1** [comment]
8.1.0 has been released.
