### ISSUE TITLE
TypeError: Cannot read property 'setEmitters' of undefined

### ISSUE THREAD

**Issue by dwowsy** [discord-akairo/discord-akairo#145]
` this.ListenerHandler.setEmitters({`         

TypeError: Cannot read property 'setEmitters' of undefined

[Main file code](https://hastebin.com/uhulilavim.js)

**Comment by Vetlix** [comment]
Yeah, we can’t help you if you don’t provide any code.

**Comment by dwowsy** [comment]
> Yeah, we can’t help you if you don’t provide more code.

Ah, my bad. [Here's the full main file.](https://hastebin.com/yozazinipe.js)

I'm assuming it's just something I did incorrectly.

**Comment by SerenModz21** [comment]
You're capitalising the L but you have defined your listener handler without a capital L. This means that it should be `this.listenerHandler.setEmitters()`.

**Comment by dwowsy** [comment]
> You're capitalising the L but you have defined your listener handler without a capital L. This means that it should be `this.listenerHandler.setEmitters({ ... })` and not `this.ListenerHandler.setEmitters({ ... })`.

That doesn't seem to be the issue, I still get the error.

**Comment by SerenModz21** [comment]
You're also setting the emitters before creating the listener handler. You should create the listener handler instance first. For example:
```js
class Client extends AkairoClient {
  constructor() {
    super( ... );

    this.listenerHandler = new ListenerHandler(this, { ... });
    this.commandHandler = new CommandHandler(this, { ... });

    this.commandHandler.useListenerHandler(this.listenerHandler);
    this.listenerHandler.setEmitters({
      commandHandler: this.commandHandler,
      listenerHandler: this.listenerHandler,
      process,
    });

    this.commandHandler.loadAll();
    this.listenerHandler.loadAll();
  }
}
```

**Comment by dwowsy** [comment]
> You're also setting the emitters before creating the listener handler. You should create the listener handler instance first. For example:
> 
> ```js
> class Client extends AkairoClient {
>   constructor() {
>     super( ... );
> 
>     this.listenerHandler = new ListenerHandler(this, { ... });
>     this.commandHandler = new CommandHandler(this, { ... });
> 
>     this.commandHandler.useListenerHandler(this.listenerHandler);
>     this.listenerHandler.setEmitters({
>       commandHandler: this.commandHandler,
>       listenerHandler: this.listenerHandler,
>       process,
>     });
> 
>     this.commandHandler.loadAll();
>     this.listenerHandler.loadAll();
>   }
> }
> ```

Ah, thanks. That fixed it. 👍
