### ISSUE TITLE
Allow users to create plugins for discord-akairo

### ISSUE THREAD

**Issue by nspeedzy** [discord-akairo/discord-akairo#152]
I was thinking of a way where users can create plugins to modify the way discord-akairo works and/or enhance it with new features by allowing users to create plugins for discord-akairo. In order to use the plugins, maybe create an `AkairoClient.use()` static method to register the plugin. I am working on creating a pull request regarding this feature request

**Comment by Papaia** [comment]
And what will the use case be?

**Comment by nerdthatnoonelikes** [comment]
Maybe people can make providers for other databases and publish them as an akairo plugin

**Comment by dioio-io** [comment]
The idea of plugins is also a good fit for a more modular framework

**Comment by nspeedzy** [comment]
@Papaia
Case 1:
let's say a user wants to integrate their dashboard more easily. I could create a plugin to integrate the user's dashboard with the akairo client.

Case 2:
Let's say someone wants to create a giveaway bot with akairo, we could create a specific giveaway plugin

**Comment by Papaia** [comment]
Why would you need `AkairoClient#use` for that?
Everything is quite possible right now.
You can just make some manager class and have `client.giveawayManager = new GiveawayManager(client);` for that.
Unless you want to hook some things into the internals, I don't get the need for such method.

**Comment by nspeedzy** [comment]
@Papaia So? we can register new plugins (if we have confirmed the plugin idea) like that without having to create a `Client.use()` method?

**Comment by nspeedzy** [comment]
Cuz I've seen other bot frameworks that have support for user created plugins.
