### ISSUE TITLE
required arguments

### ISSUE THREAD

**Issue by Sraime** [discord-akairo/discord-akairo#154]
Hello,

Maybe I'm just stupid, maybe not, but I don't understand how the error type works for arguments... In my command configuration, I just want to configure my argument as "required". 
I did this : 
```
export default class LovelyCommand extends Command {
  public constructor() {
    super("find", {
      aliases: ["cmd"],
      category: "Public Commands",
      description: {
        content: "My lovely command.",
        usage: "cmd",
        example: ["cmd"],
      },
      args: [
        {
          id: "myarg",
          type: "string",
        }
      ],
    });
  }

  async exec(message: Message, args: any): Promise<Message> {
  // some code
  }
}
```

When I use it with no parameters I get no error and my argument is null. 

Expected behavior : when the argument is not filled, the bot reply with an error message (configurable could be cool) to the user.

**Comment by Sraime** [comment]
I even tryed : 
```
args: [
        {
          id: "myarg",
          type: Agument.validate("string",(m,p,str) => str !=== null),
        }
      ],
```
But not working :(

**Comment by Shashank3736** [comment]
Use otherwise:
