### ISSUE TITLE
Plural of Discord type `roles` does not match more than one role.

### ISSUE THREAD

**Issue by rijvirajib** [discord-akairo/discord-akairo#156]
Documentation mentions:
```
All of the above types [Discord Types] also have plural forms.
So if you do users instead of user, you will receive a Collection of resolved users.
```

The wording leads me to believe that there is a plural form of `role`, being `roles`
However, when attempting to match it (even with diffferent `arg` types like `text`), the `Collection` returned is always a size of 1, containing a single role

**Comment by Mzato0001** [comment]
yes just change the match to rest or seperate (ur choice) to the type can parse all the text in the arguments
