### ISSUE TITLE
Issue when setting ownerID from environment variable on Windows

### ISSUE THREAD

**Issue by binduwavell** [discord-akairo/discord-akairo#165]
I'm using discord-akairo 8.1.0 on windows. I have an environment variable `OWNER_ID` set to my Snowflake. In my client constructor I call: 

```js
super({ ownerID: process.env.OWNER_ID });
```

Then in a command I have `ownerOnly: true,` in the options argument to `super`.

This results in the command not being invoked when it should be (called by the owner). If I remove `ownerOnly: true,` the command runs. If I update the bot constructor with:

```js
super({ ownerID: process.env.OWNER_ID.toString() });
```
and leave `ownerOnly: true,` on my command, the command works when run by the owner.

Interestingly if I call `typeof on process.env.OWNER_ID` it return `string`.

I'm not sure why this is happening, but it seems like the client constructor could do a little more to quiess the value when it is obtained from an environment variable.

**Comment by not-so-smart** [comment]
are you using typescript? Hover over `process.env.OWNER_ID` and see what the type is -- for me it shows `string | undefined`

Try narrowing the type down to `string` like so, and see if it still gives you the error?
```js
const ownerID = process.env.OWNER_ID;
if (!ownerID) throw new Error("The environment variable OWNER_ID was not set");
super({ ownerID: ownerID });
```

**Comment by binduwavell** [comment]
I'm not using typescript. In my example calling toString() on the environment c variable resolved the issue.
