### ISSUE TITLE
I've written a RedisProvider, are you interested in a contribution?

### ISSUE THREAD

**Issue by binduwavell** [discord-akairo/discord-akairo#166]
I've written a Provider for Redis. It stores JSON either directly as a serialized object or using ReJSON if the module is available in the Redis server and the associated node module is included in the project. ReJSON should provide a small performance enhancement when making adding/removing keys with large JSON blobs. I've also made the in-memory cache optional for this Provider.

**Comment by jz3r01** [comment]
I'm not the creator, but I'd say making a PR with this would be amazing :)

**Comment by binduwavell** [comment]
I've prepared PR #167 for this contribution.
