### ISSUE TITLE
Are you interested in a contribution for adding Reaction bots to Akairo?

### ISSUE THREAD

**Issue by binduwavell** [discord-akairo/discord-akairo#168]
I have a basic implementation of a ReactionHandler and Reaction that allow for Reaction "commands" to be written.

Similar to Commands, Inhibitors and Listeners, you add a ReactionHandler in your client constructor like this:

```javascript
super({ ownerID: OWNER_ID, partials: ['MESSAGE', 'CHANNEL', 'REACTION'] });
this.reactionHandler = new ReactionHandler(this, { directory: 'src/reactions/' }).loadAll();
```

Notice that for reactions to old messages to work, you have to configure discord.js with at least the three partials listed above.

Then place a file like this `log.js` into `src/reactions`:

```javascript
const Reaction = require("../struct/Reaction");
class LogReaction extends Reaction {
  constructor() {
    super('log-reactions', {});
  }
  exec(reaction, reactionType, user) {
    console.log(`User <@${user.id}> ${reactionType} ${reaction.emoji} to/from ${reaction.message.id}.`);
  }
}
module.exports = LogReaction;
```

I intend to add Inhibitors and possibly the ability to filter out reactions from bots, etc as is possible with Commands. I'm not currently planning on adding Cooldowns, Typing indication, Permissions, etc. I'm curious if folks are interested in a contribution like this and if it would be accepted as a contribution?

**Comment by Sidemen19** [comment]
Sorry, I don't quite understand what this would do. Can you please explain a bit further what it is, and why users would implement it into their bot (just an example of usage)? Thanks.

**Comment by binduwavell** [comment]
Let's say you want to implement a reaction menu. Where you have a message with a number of emojis reactions emojis at the bottom. When a user selects one of the emojis your bot is triggered and adds a role you have associated with said emoji. If the user subsequently deselects the emoji your bot could remove the associated role.

Another common use case is polls. Your bot posts a yes no question with a thumbs up and thumbs down emoji reaction. Each time a user selects the thumbs up you tally a positive vote. If they deselect you remove their vote. ND the thumbs down tallies a negative vote. 

Let's say your bot manages events. If a user selects a specific clock emoji your bot could DM that member with time information localized to their own timezone.

**Comment by ridays2001** [comment]
The reaction roles can be done by listening to the MessageReactionAdd event provided by discord.js library. Polls can either be done using the same event, or you can use awaitReactions or a Reaction Collector from the discord.js library. I don't quite understand how your handler is any different from those?

**Comment by binduwavell** [comment]
It's not different. What it does is integrate doing so the same way that that Command and CommandHandler integrate listening for the message (and possibly messageUpdate) events.

**Comment by Mzato0001** [comment]
Making a draft PR should be good @binduwavell, cause we can actually see what it does.

**Comment by binduwavell** [comment]
@Mzato0001 making this contribution will likely take me a bunch of time because I will want to setup typings (never really done this) add docs, etc. Here is a link to the commit on the branch where I'm working on this, so you can get a sense of what I'm doing: https://github.com/binduwavell/discord-akairo/commit/8192d30630434240c09a2eae1d00e3bfba03db03. I hope that helps explain what I have in mind?

**Comment by binduwavell** [comment]
The test/bot.js appears to have been broken for a while, I went ahead and got that fixed and added a sample of how to use the Reaction stuff... You can see the branch diff here: https://github.com/discord-akairo/discord-akairo/compare/master...binduwavell:add-reaction-support

**Comment by binduwavell** [comment]
I really want to add Inhibitors for reactions as well. As such I'm thinking of renaming Reaction to ReactionCommand and ReactionHandler to ReactionCommandHandler. Then We can have ReactionInhibitor and ReactionInhibitorHandler.

As an alternative, maybe Inhibitor and InhibitorHandler could be made more generic so they can inhibit Commands and Reactions.

@1Computer1 if you are interested in such a contribution, I'd love to know how you think this should be handled?
