### ISSUE TITLE
I have this error that apparently comes from the Akairo Discord Inhibitors file TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by kaname-png** [discord-akairo/discord-akairo#201]
I have tried to put conditionals to avoid that error continues to appear but it does not work

Nor do I know what inhibitor it is, it no longer tells me where the problem is, it only tells me where it originates from (source code of discord-akairo).

Any solution?
I don't know what else to do

> Error*
```ts
2021-02-14 17:19 ERROR (node:101) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null
    at CommandHandler.runAllTypeInhibitors (/home/container/kaede/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:567:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async CommandHandler.handle (/home/container/kaede/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:346:17) 
2021-02-14 17:19 ERROR (node:101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 352)
```

> This is the general structure of my bot's inhibitors
```ts
export default class NameInhibitor extends Inhibitor {
  constructor() {
    super('...', {
      reason: '...',
      type: 'post',
      category: '...',
      priority: 5,
    });
  }

  async exec(message: Message, command: Command): Promise<boolean> {
    // ..... 
  }
}
```

**Comment by Dhruvin-Purohit** [comment]
seems like a problem on your side, It is looking for <File(Inhibitor|Command|Listener)>.id which according to error implies that <File> is somehow null.

**Comment by kaname-png** [comment]
> seems like a problem on your side, It is looking for <File(Inhibitor|Command|Listener)>.id which according to error implies that is somehow null.

Hmm, it's not a problem on my side because if you look at the Discord-Akairo source code and look for that line of code that gives an error about getting the user ID

I am not looking for any user ID in that inhibitor

https://github.com/discord-akairo/discord-akairo/blob/29810b9e5d5cd804c649948ad60e5f2ac3897141/src/struct/commands/CommandHandler.js#L567:55

**Comment by Dhruvin-Purohit** [comment]
```js
} else if (this.blockClient && message.author.id === this.client.user.id) {
```
The line does not seem to error, works for me.

**Comment by kaname-png** [comment]
> ```js
> } else if (this.blockClient && message.author.id === this.client.user.id) {
> ```
> 
> The line does not seem to error, works for me.

It gives me an error how can you see, the error does not mark what is in my code, it marks what is in that file

**Comment by Dhruvin-Purohit** [comment]
That is a common mistake you see, for example, 
```sh
(node:9880) UnhandledPromiseRejectionWarning: AbortError: The user aborted a request.
    at RequestHandler.execute (/home/pi/node_modules/discord.js/src/rest/RequestHandler.js:107:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The above problem does not mean there is a problem with discord.js RequestHandler, it is just a mistake you made.

**Comment by kaname-png** [comment]
I see, but what explanation would that error I get?

**Comment by Dhruvin-Purohit** [comment]
Like i said, something wrong with your file structure I see, (maybe you forgot to export an extended class)

**Comment by kaname-png** [comment]
> Like i said, something wrong with your file structure I see, (maybe you forgot to export an extended class)

not really, that file all it does is look for a document in Mongoose and validate with a condition, and that's it

**Comment by sawa-ko** [comment]
Deprecated package.
