### ISSUE TITLE
Add support for Slash commands

### ISSUE THREAD

**Issue by edazpotato** [discord-akairo/discord-akairo#207]
# Slash commands!

Akairo should support Discord's new(ish) slash commands system.

### Possible usage
Because the number of global slash commands that a bot is allowed to have is limited, I think that making a command be available as a global slash command should be opt-in. E.g.
```js
 class SlashCommand extends Command {
   constructor() {
     super("slash", {
       slash: true,
       category: "core",
       aliases: ["slash", "sloosh"],
       clientPermissions: ["SEND_MESSAGES"]
     });
   }

  exec (message, args, slash) {
    if (slash) {
      return message.reply("You used a slash command!");
    }
    return message.reply("You used a normal command.");
  }
 }
```
As for per-guild slash commands, I'm not yet sure how you would set which guilds they're available for as these would probably need to be dynamic (for things like tags).

### Resources
- An example implementation of slash commands in a bot using Akairo is [Fire](https://github.com/FireDiscordBot/bot).
- A couple of Akairo forks that have implemented slash commands (as well as some other QoL features): [fork 1](https://github.com/SkyBlockDev/discord-akairo) [fork 2](https://github.com/NotEnoughUpdates/discord-akairo).

This feature could possibly be added in #179.

**Comment by yoon4027** [comment]
they will do that when slash commands are fully out.

**Comment by matteoturini** [comment]
Would be nice to have someone implement this.

**Comment by jackmerrill** [comment]
+1 would be nice, but should wait until fully implemented by DiscordJS.

**Comment by edazpotato** [comment]
Any updates on whether this could happen? The discord.js V13 implementation of slash commands looks pretty stable now.

I've found a couple of Akairo forks that have implemented slash commands (as well as some other QoL features): [fork 1](https://github.com/SkyBlockDev/discord-akairo) [fork 2](https://github.com/NotEnoughUpdates/discord-akairo) which could be used as a guide for implementation.

**Comment by GoldenAngel2** [comment]
I don't think this will happen until discord.js V13 is fully out. (as things can change pretty quickly)

**Comment by edazpotato** [comment]
Unfortunately, @1Computer1 has decided that slash commands won't be a part of Akairo.
[![image](https://user-images.githubusercontent.com/46797041/124131195-a8ce9e80-dad3-11eb-984b-172b8b314855.png)](https://discord.com/channels/305153029567676426/305155134445322240/849408238263730177)

I recommend looking at those forks I posted further up if you want slash commands in Akairo.

**Comment by Solixity** [comment]
Yeah.. so are slash commands still not going to be supported with discord-akairo? Cause uh.. [you *might* have a problem if you don't support them sometime soon.](https://support-dev.discord.com/hc/en-us/articles/4404772028055)

**Comment by 1Computer1** [comment]
No.
