### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Natemo6348** [discord-akairo/discord-akairo#209]
if i wanted to use this instead of commando, like changing my existing code to work with it, would it work similarly to commando, or is a lot of it different

**Comment by franciscocandido** [comment]
[Commando](https://github.com/discordjs/Commando) is a framework focused in commands and is used with [discordjs](https://discord.js.org/#/). And the [Discord Akairo](https://github.com/discord-akairo/discord-akairo) its a framework not only for commands but also the entire bot. An extension for discordjs.

So if you are going to use akairo it can be redoing your bot or in a new project.

I hope I have helped, I am learning English so there may be some mistakes even with the assistance of google translator.

**Comment by ThatGuyJamal** [comment]
> if i wanted to use this instead of commando, like changing my existing code to work with it, would it work similarly to commando, or is a lot of it different

You would need to redo your bot. Most of the login for your code will be the same, just as the commands themself. But setting up the bot will be different. Akairo uses a more `class` based system out of the box than commando, so Events, commands, and other things are handled a bit differently. 

I would just create a sample prod and test it out for yourself.

**Comment by Natemo6348** [comment]
Alright, I guess I'd better read about how it's all handled, thanks!
