### ISSUE TITLE
What is up with this "Rest" type?

### ISSUE THREAD

**Issue by TeamWolfyta** [discord-akairo/discord-akairo#214]
What's with this REST argument type not matching the rest and instead just matching to literally everything in a message... Wouldn't Rest match with the "REST" of the arguments that haven't already been matched as apposed to doing something like what "content" already does?

**Comment by TheShadowGamer** [comment]
Rest should only return the rest of the arguments. Can you send your code?

**Comment by TeamWolfyta** [comment]
Sure, This is my Argument Code
`  *args(message: Message) {
    let args = { member: null, content: null };
    args.member = yield {
      match: 'phrase',
      type: 'member',
      default: message.member,
      unordered: true,
      prompt: {
        optional: true,
      },
    };
    args.content = yield {
      match: 'rest',
      type: (_: any, phrase: string) => {
        return phrase.replace(MessageMentions.USERS_PATTERN, '').trim();
      },
      default: false,
      prompt: {
        optional: true,
      },
    };
    return args;
  }`

I Couldn't find any one else's code that works and the documentation doesn't seem to help from what ive copied.

**Comment by TheShadowGamer** [comment]
You seem to be using argument generators. Do you intend to do that? There is much simpler ways

**Comment by TeamWolfyta** [comment]
Does using Argument Generators make things behave differently or something ?

**Comment by TheShadowGamer** [comment]
It shouldn’t, but to be honest I’m not too sure how to use them other than sub commands. Why don’t you use the arguments normally?

**Comment by TeamWolfyta** [comment]
Consistency, Im a idiot when it comes to keeping things kinda the same so when i use argument generator in one file i wanna use them in all, but ive stopped doing that as of yesterday because i cannot be bothered

**Comment by TeamWolfyta** [comment]
```
      args: [
        {
          id: 'member',
          type: 'member',
          unordered: true,
          default: (message: Message) => message.member,
          prompt: {
            optional: true,
            start: 'Please Mention a Member',
            retry: 'Please Mention a valid Member',
          },
        },
        {
          id: 'colour',
          type: [...Colour_Roles.map((colour) => colour.colour)],
          default: false,
          prompt: {
            optional: true,
            start: 'Please provide a Colour',
            retry: 'Please provide a valid Colour',
          },
        },
      ],
```
Currently, I will provide a member to this and it will think im saying its a colour
