### ISSUE TITLE
Weird intents problem

### ISSUE THREAD

**Issue by NavTheSass** [discord-akairo/discord-akairo#226]
![image](https://user-images.githubusercontent.com/62173713/124698265-1c264500-df06-11eb-8674-fd5945066ad2.png)
i Suspect this to be the problem!
![image](https://user-images.githubusercontent.com/62173713/124698286-28120700-df06-11eb-94a8-58fe45114507.png)

**Comment by almeidx** [comment]
The intersection type should probably be replaced with a union type

**Comment by ShockTr** [comment]
This was fixed on #216
