### ISSUE TITLE
Discord.JS V13 problem with Discord-Akairo

### ISSUE THREAD

**Issue by yassine955** [discord-akairo/discord-akairo#237]
'"discord.js"' has no exported member named 'StringResolvable'. Did you mean 'UserResolvable'?

This is the message i get

These are the dependency i use:

`"dependencies": {
    "discord-akairo": "^8.1.0",
    "discord.js": "^13.1.0"
  },`

**Comment by GoldenAngel2** [comment]
Use the master branch
```bash
npm i discord-akairo/discord-akairo
```

**Comment by yassine955** [comment]
As GoldenAngel2 stated: `npm i discord-akairo/discord-akairo`

This is the solution!!!
