### ISSUE TITLE
InteractionCreate event is not triggering.

### ISSUE THREAD

**Issue by yassine955** [discord-akairo/discord-akairo#238]
The interactionCreate is not triggering, when I type `/ping` in discord. The other event like `messageCreate` works fine, anyone has a solution?

```
import { Listener } from "discord-akairo";
import { Interaction, MessageActionRow, MessageButton } from "discord.js";

export default class interactionCreate extends Listener {
  public constructor() {
    super("interactionCreate", {
      emitter: "client",
      event: "interactionCreate",
      category: "client",
    });
  }

  public async exec(interaction: Interaction) {
    if (!interaction.isCommand()) return;

    if (interaction.commandName === "ping") {
      const row = new MessageActionRow().addComponents(
        new MessageButton()
          .setCustomId("primary")
          .setLabel("Primary")
          .setStyle("PRIMARY")
      );

      await interaction.reply({ content: "Pong!", components: [row] });
    }
  }
}

```

**Comment by yassine955** [comment]
I have seen on this Documentation https://discordjs.guide/interactions/registering-slash-commands.html#guild-commands, but did Discord Akairo already implement this?

**Comment by SerenModz21** [comment]
make sure u have the `GUILD_INTEGRATIONS` intent

**Comment by yassine955** [comment]
I have the `GUILD_INTEGRATIONS`

**Comment by yassine955** [comment]
```
public constructor(config: BotOptions) {
    super(
      {
        ownerID: config.owners,
      },
      {
        intents: [
          Intents.FLAGS.GUILDS,
          Intents.FLAGS.GUILD_MESSAGES,
          Intents.FLAGS.GUILD_INTEGRATIONS,
        ],
      }
    );
    this.config = config;
  }
```

**Comment by rizzdev** [comment]
@yassine955 

Hi, sorry to pop in on an unrelated subject, but how did you use esm imports? I am getting an error when I try to do that. 

https://i.imgur.com/HcsrsUC.jpeg

**Comment by SerenModz21** [comment]
> ```
> public constructor(config: BotOptions) {
>     super(
>       {
>         ownerID: config.owners,
>       },
>       {
>         intents: [
>           Intents.FLAGS.GUILDS,
>           Intents.FLAGS.GUILD_MESSAGES,
>           Intents.FLAGS.GUILD_INTEGRATIONS,
>         ],
>       }
>     );
>     this.config = config;
>   }
> ```

I'm not sure, it should be working, u might have to try and do some debugging to see if u can figure out what is happening

**Comment by SerenModz21** [comment]
> @yassine955
> 
> Hi, sorry to pop in on an unrelated subject, but how did you use esm imports? I am getting an error when I try to do that.
> 
> https://i.imgur.com/HcsrsUC.jpeg

they are using typescript, for javascript you would have to google it

i know babel or swc can be used but looking at the node docs (https://nodejs.org/api/esm.html) it looks like u can use the `.mjs` file extension to ue them

**Comment by Syrup** [comment]
> The interactionCreate is not triggering, when I type `/ping` in discord. The other event like `messageCreate` works fine, anyone has a solution?
> 
> ```
> import { Listener } from "discord-akairo";
> import { Interaction, MessageActionRow, MessageButton } from "discord.js";
> 
> export default class interactionCreate extends Listener {
>   public constructor() {
>     super("interactionCreate", {
>       emitter: "client",
>       event: "interactionCreate",
>       category: "client",
>     });
>   }
> 
>   public async exec(interaction: Interaction) {
>     if (!interaction.isCommand()) return;
> 
>     if (interaction.commandName === "ping") {
>       const row = new MessageActionRow().addComponents(
>         new MessageButton()
>           .setCustomId("primary")
>           .setLabel("Primary")
>           .setStyle("PRIMARY")
>       );
> 
>       await interaction.reply({ content: "Pong!", components: [row] });
>     }
>   }
> }
> ```

try changing `import { Interaction, ... } from "discord.js"` to `import { CommandInteraction, ... } from "discord.js"`
see https://discord.js.org/#/docs/main/stable/class/CommandInteraction
