### ISSUE TITLE
Cannot execute commands without basic intents 

### ISSUE THREAD

**Issue by MaheshNat** [discord-akairo/discord-akairo#247]
After upgrading to the most recent version of discord-akairo and discord.js, I was confused when my bot did not reply to any commands. It turns out the intents ['GUILDS', 'GUILD_MESSAGES'] are basic requirements for commands to work. I would recommend this be put somewhere in the documentation, or if it already is, please let me know. Or, if there is a better way of doing things that doesn't require these intents to be specified manually, let me know.

Just wanted to point out a breaking change for bots between discord.js v12 and v13.

**Comment by xhyrom** [comment]
It's because discord API v9. You need define intent GUILD_MESSAGES for emitting MESSAGE_CREATE event by discord, messageCreate in djs

**Comment by MaheshNat** [comment]
got it, thanks for clarifying.
