### ISSUE TITLE
SQLiteProvider.set is saved in db file, but not loaded when bot is restarted

### ISSUE THREAD

**Issue by IzaacJ** [discord-akairo/discord-akairo#60]
Hello.
Using SQLiteProvider as described in [the docs](https://discord-akairo.github.io/#/docs/main/stable/other/providers) but after a restart of my bot the values in the db file isn't loaded so all values are empty.

I setup the provider like this:
```
this.settings = new SQLiteProvider(sqlite.open('./data/verifier.sqlite'), 'verifier', {
    idColumn: 'guild_id',
    dataColumn: 'settings'
});
```
Initializing the provider:
```
login(token) {
    return this.settings.init().then(() => super.login(token));
}
```

And I set/get the settings like this:
```
// Setting guild name
this.client.settings.set(message.guild.id, "guild-name", args.value);

// Getting guild name
var v = this.client.settings.get(message.guild.id, "guild-name", "[None]");
```

And it always returns `"[None]"` after a restart of the bot. Before the restart it returns the correct value. And I've verified that the value is actually stored in the db file with [DB Browser for SQLite](https://sqlitebrowser.org/).

Any ideas what the issue could be?

**Comment by pizzafox** [comment]
Are you hosting your boy somewhere that doesn't persist files? Hosts like Heroku will wipe your instance each day and download files from GitHub, including your database file.
