### ISSUE TITLE
Error Receiving path

### ISSUE THREAD

**Issue by OperationInactive** [discord-akairo/discord-akairo#63]
After following the setup instructions for the command directory I get this as an error.
> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

My exact code: 
` const { AkairoClient, CommandHandler } = require('discord-akairo');
class MyClient extends AkairoClient {
    constructor() {
        super({
            ownerID: '123992700587343872', // or ['123992700587343872', '86890631690977280']
        }, {
            disableEveryone: true
        });
        this.commandHandler = new CommandHandler(this, {
            directory: './commands/',
            prefix: '?' // or ['?', '!']
        });
        this.commandHandler.loadAll();
    }
}
const client = new MyClient();
client.login('mytoken')`

**Comment by 1Computer1** [comment]
Make sure you are on correct version of the guide for your installation.

**Comment by OperationInactive** [comment]
I followed all the steps for the master guide. 
As that's the install that I did.

**Comment by VisualDevelopment** [comment]
the installation guide on the master's docs are incorrect, try installing using `npm install discord-akairo/discord-akairo --save`
