### ISSUE TITLE
InhibitorOptions 'type' type should be string

### ISSUE THREAD

**Issue by qwright10** [discord-akairo/discord-akairo#68]
The type of 'type' in InhibitorOptions is a boolean but should be a string on the discord akairo website

**Comment by Fyk0** [comment]
So make a PR 🤔

**Comment by Monbrey** [comment]
The typings are correct everywhere in the source code, current master. Do the docs just need to be rebuilt from source?

**Comment by qwright10** [comment]
My PR to fix the issue was merged but this issue wasn't closed. The docs still have the incorrect type, so I think they should be rebuilt.
