### ISSUE TITLE
Suggestion: Undo Command

### ISSUE THREAD

**Issue by Haxified** [discord-akairo/discord-akairo#70]
Have an optional extendable function in the command class called "undo", Akairo will detect when a user runs (prefix)undo (customizable?), and if the function is extended, run the undo function in the last ran command by the author

**Comment by devcat** [comment]
discord akairo is command framework, user should be the one implementing commands not framework

you can already do this yourself by adding undo function to commands and having undo command that executes that function

**Comment by Haxified** [comment]
fair enough, i had some more ideas on how you would implement this but whatever, i'll close this
