### ISSUE TITLE
Listener.client.commandHandler returns undefined

### ISSUE THREAD

**Issue by qwright10** [discord-akairo/discord-akairo#77]
`this.client.commandHandler` returns `undefined` in a Listener, but returns the command handler in a Command.

**Comment by 1Computer1** [comment]
Please include a minimal reproducible code sample.

**Comment by qwright10** [comment]
`const command = this.client.commandHandler.modules.get('note-show');
return this.client.commandHandler.runCommand(message, command!, await command!.parse(message, message.util!.parse!.afterPrefix));`

**Comment by Monbrey** [comment]
Unable to reproduce this
```js
export default class ReadyListener extends Listener {
    constructor() {
        super("ready", { emitter: "client", event: "ready" });
    }

    public async exec() {
        console.log(this.client.commandHandler.constructor.name);
    }
}
```
Output is `CommandHandler`
