### ISSUE TITLE
CommandUtil enabled - Getting Cannot read property 'transformOptions' of undefined

### ISSUE THREAD

**Issue by Silentz0r** [discord-akairo/discord-akairo#80]
Hi,

index.js
```
const { AkairoClient, CommandHandler } = require('discord-akairo');
...
this.commandHandler = new CommandHandler(this, {
            directory: './commands/',
            prefix: '*', // or ['?', '!'],
            commandUtil: true,
            handleEdits: true
        });
this.commandHandler.loadAll();
...
```

Using the snippet [here](https://discord-akairo.github.io/#/docs/main/8.0.0-beta.8/snippets/ping)

I'm getting this error: 
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'transformOptions' of undefined
```
If i use the normal `message.reply` it works just the reply. Perhaps i'm doing something wrong?

version installed:
```
discord-akairo: 8.0.0-beta.8
discord.js: 11.5.1
```

Any help would be appreciated, thank you.

**Comment by devcat** [comment]
beta requires discord.js v12 aka master branch

**Comment by Silentz0r** [comment]
> 8.0.0 requires discord.js v12 aka master branch

Fixed installing the master version, thank you. Closing.
