### ISSUE TITLE
possible to have timeout and cancel prompt edit the last start or retry?

### ISSUE THREAD

**Issue by zfbx** [discord-akairo/discord-akairo#83]
I'm currently using 
```js
prompt: {
    modifyStart: (message, text) => {
        return `${text}\n\`Type exit to cancel this command.\``;
    },
    cancelWord: 'exit',
    cancel: 'Command has been cancelled.',
}
```
in my commandHandler and when i type exit to cancel the command it creates a new message saying the command has been canceled or when the message times out it puts a new message saying the command has been canceled. Can I make it where instead of creating a new message it edits the last message instead? I feel it'd be much cleaner and remove some confusion compared to when the prompt question is still visible.

**Comment by TitusEntertainment** [comment]
As far as I'm aware, there is currently no way to do this. If you really want it you can make a pr following the template.

**Comment by zfbx** [comment]
Ah.. okay, yeah I don't even know where to begin on how to implement that. but alright, thanks.
