### ISSUE TITLE
How to take a command with a string of text with spaces as an argument?

### ISSUE THREAD

**Issue by zfbx** [discord-akairo/discord-akairo#84]
I have the need to take a string as input for example with a ban command I want a reason so the command being `!ban 354835091211419648 For doing something bad` as an advanced example but  even something simple like `!say Hi there person` 

if I do something like
```js
args: [
    {
        id: 'msg',
        type: 'string', //I tried 'content' too
        prompt: {
            start: 'What do you want to say?',
            retry: 'Try again',
            optional: false
        },
    }
],
```

It will work only if I let the prompt pop up, but if I try to just the command at once it only grabs the first word. Am I doing something wrong?

**Comment by devcat** [comment]
use match field
https://discord-akairo.github.io/#/docs/main/stable/typedef/ArgumentOptions
https://discord-akairo.github.io/#/docs/main/stable/typedef/ArgumentMatch

**Comment by zfbx** [comment]
Thank you! that's exactly what I needed. There should be an example of this in the arguments section of the docs https://discord-akairo.github.io/#/docs/main/master/arguments/arguments
