### ISSUE TITLE
cooldown listener issues?

### ISSUE THREAD

**Issue by zfbx** [discord-akairo/discord-akairo#85]
I can't seem to trigger a warning with a command with a cooldown so i set up a listener like this 

```js
const { Listener } = require('discord-akairo');

class CommandCooldownListener extends Listener {
    constructor() {
        super('commandCooldown', {
            emitter: 'commandHandler',
            event: 'commandCooldown'
        });
    }

    async exec(message, command, reason) {
        console.log(`${message.author.user} triggered a cooldown from using ${command.id} because of ${reason}`);
    }
}
module.exports = CommandCooldownListener;
```
and this triggers a `AkairoError [INVALID_TYPE]: Value of 'emitter' was not an EventEmitter` error
if i use client as the emitter that does nothing.

I read somewhere that you need to add extra classes as `classToHandle` under the ListenerHandle but I couldn't seem to get that to work either. am I making some rookie mistake or is something changed about the cooldown system? I can't find any other examples online

**Comment by ItsPapaia** [comment]
What version are you on? If on master/beta, you have to specify the emitters yourself (except `client`) with [ListenerHandler#setEmitters](https://discord-akairo.github.io/#/docs/main/master/class/ListenerHandler?scrollTo=setEmitters)

**Comment by GamesProSeif** [comment]
Adding on the previous comment, there's also the [listener guide](https://discord-akairo.github.io/#/docs/main/master/basics/listeners) that will help you set it up.
Also [CommandHandler#commandCooldown](https://discord-akairo.github.io/#/docs/main/stable/class/CommandHandler?scrollTo=e-commandCooldown) (on stable) has been renamed to [CommandHandler#cooldown](https://discord-akairo.github.io/#/docs/main/master/class/CommandHandler?scrollTo=e-cooldown) (on master).

**Comment by zfbx** [comment]
okay cool, finally got it, that was confusing. I ended up running into another problem with zucc that silently stopped my bot from connecting which was a pain but for future people who come across this issue this is what I changed (Master version) In the listener:
```js
class cooldownListener extends Listener {
    constructor() {
        super('cooldown', {
            emitter: 'commandHandler',
            event: 'cooldown'
        });
    }
```
and in my client constructor I have this now:
```js
this.commandHandler.useInhibitorHandler(this.inhibitorHandler);
this.commandHandler.useListenerHandler(this.listenerHandler);
this.listenerHandler.setEmitters({
    client: this, //don't know if this is required but doesn't error when included
    commandHandler: this.commandHandler,
    inhibitorHandler: this.inhibitorHandler,
    listenerHandler: this.listenerHandler,
});
this.commandHandler.loadAll();
this.listenerHandler.loadAll();
this.inhibitorHandler.loadAll();
```
Thanks for you help guys :) so many very helpful people in this community <3

**Comment by ItsPapaia** [comment]
Happy to help!
Also, the `client: this` is useless since it's automatically added [here](https://github.com/discord-akairo/discord-akairo/blob/8.0.0-beta.8/src/struct/listeners/ListenerHandler.js#L39), in the ListenerHandler constructor.
