### ISSUE TITLE
Typing of this.client inside of commands

### ISSUE THREAD

**Issue by OrangeDrangon** [discord-akairo/discord-akairo#86]
When using this.client inside of a command in typescript the typing is AkairoClient when it should be the custom client class.

**Comment by Jo3-L** [comment]
I believe that this is intended, as there's no way for Akairo to dynamically type `AkairoModule#client` as your extended client class. What you do is (for example, in your extended client file):
```ts
declare module 'discord-akairo' {
   interface AkairoClient {
        commandHandler: CommandHandler;
       // etc...
   }
}
```
Now, when you import AkairoClient it'll have your addons (meaning that `AkairoModule#client` will now contain that as well).

I hope this helped a little :)
