### ISSUE TITLE
Typing : MessageAdditions is not exported

### ISSUE THREAD

**Issue by minhducsun2002** [discord-akairo/discord-akairo#93]
```
> boomer@0.0.1 build /tmp/build_5f489609686e90e25aa7a2e12f79b066
> tsc

node_modules/discord-akairo/src/index.d.ts(5,9): error TS2724: Module '"discord.js"' has no exported member 'MessageAdditions'. Did you mean 'MessageEditOptions'?
```

Discord.js 11.5.1, TypeScript 3.7.5, commit cb458b3a9b8b8fd944dd9c0ebed89268c5cd91f5 (`8.0.0beta8` if I am right) for reference

**Comment by ItsPapaia** [comment]
You're using Akairo master/beta with discord.js stable.
Master exports MessageAdditions [here](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L2419), stable never exports it, and it's not in the docs either.

**Comment by minhducsun2002** [comment]
Looks like `discord.js` on `master` fixed it. Closing issue.

**Comment by ItsPapaia** [comment]
Note: master has ~~some~~ a lot of breaking changes, check those out if you're migrating.

**Comment by minhducsun2002** [comment]
Thank you. Having used both versions, I am fully aware of that.
