### ISSUE TITLE
Feature request : exposing Command.args

### ISSUE THREAD

**Issue by minhducsun2002** [discord-akairo/discord-akairo#96]
For "help" commands, it would be nice if `Command.args` gets exposed for parsing.

**Comment by 1Computer1** [comment]
This is not possible since it is compiled to a generator. Generator arguments would also not be useful to expose. I recommend you write documentation by hand, anyways.

**Comment by ItsPapaia** [comment]
Can always extend Command and add it as a property in the constructor.

**Comment by minhducsun2002** [comment]
Thank you for reminding, it completely slipped off my mind.
